### ISSUE TITLE
Could not find ‘train.fea‘ file？

### ISSUE THREAD

**Issue by Lynlzz1314** [mawahballah/ApplicationsandEnhancementsoftheDeepRecurrentNeuralNetworkForSpeechSeparation#1]
Hello,
I was going through your repository. I could not find train.fea file generated by you. Can you please add it?

**Comment by mawahballah** [comment]
Hello,
Sorry for the late reply, it should get generated for you when you run the demo.

**Comment by Lynlzz1314** [comment]
@mawahballah 
    Hi,
   When running the run_test_single_model.m , there are some errors:
/bin/sh: HCopy: command not found
Error using htkread (line 20)
Unable to read from file ../../..//codes/TSP/demo/results/train.fea
Error in compute_features (line 54)
        [ DATA, HTKCode ] = htkread( [eI.saveDir,'train.fea'] );
Error in formulate_data_test (line 49)
    [DATA, mixture_spectrum, eI]=compute_features(dmix, eI);
Error in test_TSP_general_kl_recurrent (line 26)
    [test_data_cell, target_ag, mixture_spectrum]=formulate_data_test(mixture, eI, testmode);
Error in run_test_single_model (line 34)
    test_TSP_general_kl_recurrent(eI.modelname, theta, eI, 'done', j);
 Can you answer the above questions?

**Comment by mawahballah** [comment]
This happens because you don't have HTK installed.
please install HTK here: http://htk.eng.cam.ac.uk/
Also to install HTK you need to add the path to vcvars32.bat to the system path(if you have visual studio 2017, you can find it here: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build")
You might face some difficulty while installing HTK as well because it's not mentioned in the steps that you should run the cmd as administrator. 
Goodluck

**Comment by Lynlzz1314** [comment]
If multi-speakers in a low voice as background noise, can it separate the desired target speech from the background noise?

**Comment by mawahballah** [comment]
not completely, it can mainly separate a desired speaker's speech from multiple speakers' speech.

**Comment by Lynlzz1314** [comment]
Thanks
