### ISSUE TITLE
logmel feature training error

### ISSUE THREAD

**Issue by sharrrboy** [mawahballah/ApplicationsandEnhancementsoftheDeepRecurrentNeuralNetworkForSpeechSeparation#2]
Hello sir, when I use training code for logmel feature (MFCCorlogMelorSpectrum=1) I encounter the following errors:                              ,                                                                                 model_RNN1_win1_h300_l2_r0_64ms_100000_softabs_linearout_RELU_logmel_trn0_c1e-10_c0.001_bsz10000_miter10_bf50_c0_d0
Global iterations: 1
1 1561598, 1 0, 1561598
'HCopy' is not recognized as an internal or external command, 
operable program or batch file. 
Error using htkread (line 20)
Unable to read from file
../../\codes\TSP\discrim_joint_offset_all_results\model_RNN1_win1_h300_l2_r0_64ms_100000_softabs_linearout_RELU_logmel_trn0_c1e-10_c0.001_bsz10000_miter10_bf50_c0_d0\train.fea

Error in compute_features (line 54)
        [ DATA, HTKCode ] = htkread( [eI.saveDir,'train.fea'] );

Error in formulate_data (line 44)
        [DATA, mixture_spectrum, eI]=compute_features(dmix, eI);

Error in train_TSP_demo_mini_clip (line 234)
        [data_cell, targets_cell, mixture_spectrum]=formulate_data(train1, train2_shift, eI, eI.train_mode); %0 -- chunk, 2--no chunk

Error in Untitled_3 (line 46)
train_TSP_demo_mini_clip(context_win, hidden_units, num_layers, isdropout, isRNN, iscleanonly,...

**Comment by mawahballah** [comment]
Hi,
Sorry I just saw this.
This happens because you don't have HTK installed.
please install HTK here: http://htk.eng.cam.ac.uk/
Also to install HTK you need to add the path to vcvars32.bat to the system path(if you have visual studio 2017, you can find it here: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build")
You might face some difficulty while installing HTK as well because it's not mentioned in the steps that you should run the cmd as administrator.
Goodluck
